### ISSUE TITLE
Not valid with v1.4.4?

### ISSUE THREAD

**Issue by tommbf2** [akhoury/nodebb-plugin-mailchimp#5]
is this not valid with 1.4.4?

ive installed and uninstalled many times but doesn't show on plugins page?

**Comment by akhoury** [comment]
probably not, i'll check it out when i get a chance, for now, you can manually update your mailchimp list by downloading the users CSV file from the nodebb admin panel > Manage > Users and uploading to mailchimp

![screen shot 2017-03-22 at 6 24 14 pm](https://cloud.githubusercontent.com/assets/1398375/24208703/f488ae32-0f2c-11e7-9bc5-d1d82dfe865b.png)

**Comment by ayxos** [comment]
Hi, Is this still not valid? Thanks
