### ISSUE TITLE
Update the plugin to 1.12.2

### ISSUE THREAD

**Issue by Jenkler** [akhoury/nodebb-plugin-mailchimp#6]
The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin

**Comment by akhoury** [comment]
there, use version [0.3.3](https://www.npmjs.com/package/nodebb-plugin-mailchimp)
commits: 
https://github.com/akhoury/nodebb-plugin-mailchimp/commit/ef2853836bca7d6ff193d6ef492d821ac0873aa1
https://github.com/akhoury/nodebb-plugin-mailchimp/commit/e84981cca675cbbdf2fc58a695d4c2c1cecdd45b

**Comment by Jenkler** [comment]
Thanks :+1:
